// This file is auto-generated by @hey-api/openapi-ts

export const $FileUploadDto = {
    type: 'object',
    properties: {
        file: {
            type: 'string',
            format: 'binary',
        },
    },
    required: ['file'],
} as const

export const $AnalyzeResultItemDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
        },
        name: {
            type: 'string',
        },
        carbs: {
            type: 'number',
        },
        cal: {
            type: 'number',
        },
        fat: {
            type: 'number',
        },
        protein: {
            type: 'number',
        },
        weight: {
            type: 'number',
        },
    },
    required: ['id', 'name', 'carbs', 'cal', 'fat', 'protein', 'weight'],
} as const

export const $AnalysisResultDto = {
    type: 'object',
    properties: {
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/AnalyzeResultItemDto',
            },
        },
    },
    required: ['items'],
} as const
